name = "DiplodocusCollisions"
uuid = "32d0d58a-4da0-4f8e-8b7e-c2816ac6e5cb"
authors = ["Christopher Everett and contributors"]
version = "0.0.2"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
BenchmarkTools = "1.6.0"
Bessels = "0.2.8"
JLD2 = "0.5.15"
ProgressMeter = "1.10.4"
julia = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
