name = "DiplodocusCollisions"
uuid = "32d0d58a-4da0-4f8e-8b7e-c2816ac6e5cb"
version = "0.2.0"
authors = ["Christopher Everett and contributors"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
BenchmarkTools = "1.6"
Bessels = "0.2"
JLD2 = "0.6"
ProgressMeter = "1.10"
Random = "1.11"
Revise = "3.12.3"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
